# Site settings
author: Janay 
title: JoinJanay
header-img: img/home-bg.png
email: tjanay87@gmail.com
copyright_name: Janay 
description: > # this means to ignore newlines until "baseurl:"
  Curiosity led you here... go ahead and join me on my journey 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: JoinJanay_JS
github_username:  JoinJanay-JS

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
